# Generated by Django 3.2.11 on 2022-01-13 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
                ('birthdate', models.CharField(max_length=6)),
                ('phone_number', models.CharField(max_length=4)),
            ],
        ),
    ]
